<?php
/**
 * @var \Gaiterjones\AjaxButton\Block\AjaxButton $block
 */
$_debug=true;
$_ajaxurl=$block->getAjaxUrl();
$_ajaxButtonId=$block->getAjaxButtonId();
$_ajaxWrapperClass=$block->getAjaxWrapperClass();
$_ajaxGetButtonData=$block->ajaxGetButtonData();
$_ajaxGetActionData=$block->ajaxGetActionData();
?>
<?php if($_debug): ?>
<pre>
    GJ AJAXBUTTON DEBUG
    <?php print_r($_ajaxGetButtonData); ?>
    <?php print_r($_ajaxGetActionData); ?>
</pre>
<?php endif; ?>
<div id="gj-ajaxbutton-wrapper-<?php echo $_ajaxButtonId; ?>" class="gj-ajaxbutton-wrapper <?php echo $_ajaxWrapperClass; ?>">
    <svg version="1.1" id="L9" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
      viewBox="0 0 100 100" enable-background="new 0 0 0 0" xml:space="preserve">
        <path fill="#D3D3D3" d="M73,50c0-12.7-10.3-23-23-23S27,37.3,27,50 M30.9,50c0-10.5,8.5-19.1,19.1-19.1S69.1,39.5,69.1,50">
          <animateTransform
             attributeName="transform"
             attributeType="XML"
             type="rotate"
             dur="1s"
             from="0 50 50"
             to="360 50 50"
             repeatCount="indefinite" />
      </path>
    </svg>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Gaiterjones_AjaxButton/js/gj-ajaxbutton": {
                "AjaxUrl": "<?php echo $_ajaxurl; ?>",
                "AjaxData": <?php echo json_encode($_ajaxGetButtonData);?>,
                "AjaxButtonId": "<?php echo $_ajaxButtonId; ?>"
            },
            "Gaiterjones_AjaxButton/js/gj-ajaxbutton-action": {
                "AjaxUrl": "<?php echo $_ajaxurl; ?>",
                "AjaxData": <?php echo json_encode($_ajaxGetActionData);?>,
                "AjaxButtonId": "<?php echo $_ajaxButtonId; ?>"
            }
        }
    }
</script>
