<?php
/**
 * @var \Gaiterjones\AjaxButton\Block\AjaxButton $block
 */
$_debug=true;
$_ajaxurl=$block->getAjaxUrl();
$_ajaxButtonId=$block->getAjaxButtonId();
$_ajaxGetButtonData=$block->ajaxGetButtonData();
$_ajaxGetActionData=$block->ajaxGetActionData();
?>
<?php if($_debug): ?>
<pre>
    GJ AJAXBUTTON DEBUG
    <?php print_r($_ajaxGetButtonData); ?>
    <?php print_r($_ajaxGetActionData); ?>
</pre>
<?php endif; ?>
<div id="gj-ajaxbutton-wrapper-<?php echo $_ajaxButtonId; ?>" style="border: 2px solid #e6e2e2; padding: 25px; border-radius: 25px;">
    <i style="color: #e6e2e2;" class="fa fa-cog fa-spin fa-2x fa-fw"></i>
    <span class="sr-only"><?php echo __('Loading')?>...</span>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Gaiterjones_AjaxButton/js/gj-ajaxbutton": {
                "AjaxUrl": "<?php echo $_ajaxurl; ?>",
                "AjaxData": <?php echo json_encode($_ajaxGetButtonData);?>,
                "AjaxButtonId": "<?php echo $_ajaxButtonId; ?>"
            },
            "Gaiterjones_AjaxButton/js/gj-ajaxbutton-action": {
                "AjaxUrl": "<?php echo $_ajaxurl; ?>",
                "AjaxData": <?php echo json_encode($_ajaxGetActionData);?>,
                "AjaxButtonId": "<?php echo $_ajaxButtonId; ?>"
            }
        }
    }
</script>
